const env = {
	CLASSROOMDOOR_WEB_URL: process.env.CLASSROOMDOOR_WEB_URL,

	OPENVIDU_SERVER_URL: process.env.OPENVIDU_URL,

	OPENVIDU_SERVER_SECRET: process.env.OPENVIDU_SECURITY_TOKEN,

	STRIPE_KEY: process.env.STRIPE_KEY,

	STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,

	FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,

	FIREBASE_CERT_KEY: process.env.FIREBASE_CERT_KEY,

	PROJECT_ID: process.env.PROJECT_ID,

	CLASSROOMDOOR_SUPPORT_EMAIL: process.env.CLASSROOMDOOR_SUPPORT_EMAIL,
	API_ACCESS_SECRET: process.env.API_ACCESS_SECRET || false,
};

export default env;
