// Booking Requests Status
export const BOOKING_REQUEST_STATUS_CODES = {
	WAITING_FOR_TEACHER_CONFIRMATION: 1,
	WAITING_FOR_STUDENT_CONFIRMATION: 2,
	ACCEPTED: 4,
	CANCELLED: 6,
	REJECTED: 7,
	PAYMENT_PROCESSING: 8,
	PAYMENT_FAILED: 9,
	CONFIRMED: 10,
};

export const EPICBOARD_SESSION_STATUS_CODES = {
	CREATED: 1,
	STARTED: 2,
	ACTIVE: 3,
	ENDED: 4,
	NO_SHOW: 5,
	CANCELLED: 6,
};

export const EPICBOARD_ROOM_STATUS_CODES = {
	CREATED: 1,
	ACTIVE: 2,
	ARCHIVED: 3,
};
