


// Booking Requests Status
export const BOOKING_REQUEST_STATUS_CODES = {
    WAITING_FOR_TEACHER_CONFIRMATION: 1,
    WAITING_FOR_STUDENT_CONFIRMATION: 2,
    ACCEPTED: 3,
    CANCELLED: 4,
    CONFIRMED: 5,
}

